# Generated by Django 5.0.2 on 2024-05-06 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='friendship_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
