# Generated by Django 5.0.2 on 2024-05-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_images')),
                ('firebase_user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('friends', models.ManyToManyField(blank=True, to='api_users.userprofile')),
                ('friendship_requests', models.ManyToManyField(blank=True, related_name='received_requests', to='api_users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_lesson_reminders', models.BooleanField(default=True)),
                ('friend_request_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_users.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
