# Generated by Django 5.0.2 on 2024-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_usermodel_user_type_alter_usermodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
