# Generated by Django 5.0.2 on 2024-05-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0004_remove_usermodel_image_usermodel_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=models.TextField(default='No Bio Yet', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
