# Generated by Django 5.0.2 on 2024-05-08 04:44

import protected_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0005_alter_usermodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=protected_media.models.ProtectedImageField(blank=True, null=True, storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='user_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото (Firebase)'),
        ),
    ]
