# Generated by Django 5.0.2 on 2024-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0007_usermodel_day_streak_usermodel_last_login_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_login_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний вход!!'),
        ),
    ]
