# Generated by Django 5.0.2 on 2024-05-14 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0008_alter_usermodel_last_login_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login_datetime',
        ),
        migrations.AlterField(
            model_name='useractivitydatemodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата активности'),
        ),
    ]
