# Generated by Django 5.0.2 on 2024-05-14 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0009_remove_usermodel_last_login_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointaddhistory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
