# Generated by Django 5.0.2 on 2024-05-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0010_alter_userpointaddhistory_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitydatemodel',
            options={'ordering': ['-datetime'], 'verbose_name': 'Активность пользователя', 'verbose_name_plural': 'Активности пользователей'},
        ),
    ]
