# Generated by Django 5.0.2 on 2024-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0014_alter_usermodel_managers_usermodel_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
