# Generated by Django 5.0.2 on 2024-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0017_deletedusersmodel_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'verbose_name': 'Настройки уведомлений', 'verbose_name_plural': 'Настройки уведомлений'},
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='friend_request_notifications',
            new_name='friend_request_notification',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='periodic_lesson_reminders',
            new_name='global_event_notification',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='periodic_lesson_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='strike_notification',
            field=models.BooleanField(default=True),
        ),
    ]
