# Generated by Django 5.0.2 on 2024-06-16 20:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0019_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='timezone_type',
            field=models.CharField(default='UTC', max_length=16, verbose_name='Часовой пояс'),
        ),
    ]
