# Generated by Django 5.0.2 on 2024-06-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0021_remove_usermodel_timezone_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='strike_notification',
            new_name='streak_notification',
        ),
    ]
