# Generated by Django 5.0.2 on 2024-06-16 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0022_rename_strike_notification_notificationsettings_streak_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='last_lesson_reminder',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='last_streak_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
