# Generated by Django 5.0.2 on 2024-06-16 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0023_notificationsettings_last_lesson_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='last_lesson_reminder',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='last_streak_notification',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0)),
        ),
    ]
