# Generated by Django 5.0.2 on 2024-05-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalMaterial',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_number',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_lessons.lessonbatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lessons.lesson'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lessons.question'),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
