# Generated by Django 5.0.2 on 2024-05-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0003_lessonbatch_question_questionanswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonbatch',
            options={'verbose_name': 'Коллекция уроков', 'verbose_name_plural': 'Коллекции уроков'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
    ]
