# Generated by Django 5.0.2 on 2024-05-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0004_alter_lesson_options_alter_lessonbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_available_on_free',
            field=models.BooleanField(default=False, verbose_name='Доступен на бесплатном тарифе'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lessons.lessonbatch', verbose_name='Коллекция уроков'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lessons.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lessons.question', verbose_name='Вопрос'),
        ),
    ]
