# Generated by Django 5.0.2 on 2024-05-06 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0006_userquestionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api_lessons.lessonbatch', verbose_name='Коллекция уроков'),
        ),
    ]
