# Generated by Django 5.0.2 on 2024-05-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0007_alter_lesson_lesson_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbatch',
            name='title',
            field=models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('addition', 'Additional')], max_length=255, verbose_name='Название коллекции уроков'),
        ),
    ]
