# Generated by Django 5.0.2 on 2024-05-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0009_alter_question_lesson_alter_questionanswer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
