# Generated by Django 5.0.2 on 2024-05-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0011_conspectuscomponent_videocomponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncomponent',
            name='lesson',
        ),
    ]
