# Generated by Django 5.0.2 on 2024-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0014_alter_lessoncomponent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncomponent',
            name='type',
            field=models.CharField(choices=[('video', 'Видео'), ('question', 'Вопрос'), ('conspectus', 'Конспект')], max_length=20, verbose_name='Тип компонента'),
        ),
    ]
