# Generated by Django 5.0.2 on 2024-05-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0015_alter_lessoncomponent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlessonmodel',
            name='progress',
        ),
        migrations.AddField(
            model_name='userlessonmodel',
            name='is_lesson_completed',
            field=models.BooleanField(default=False, verbose_name='Урок завершен'),
        ),
    ]
