# Generated by Django 5.0.2 on 2024-05-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0016_remove_userlessonmodel_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlessonmodel',
            old_name='is_lesson_completed',
            new_name='completed',
        ),
    ]
