# Generated by Django 5.0.2 on 2024-05-22 19:38

import django.db.models.deletion
import protected_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0019_alter_lesson_options_lesson_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillTextComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заполните текст', max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заполните текст компонент',
                'verbose_name_plural': 'Заполните текст компоненты',
            },
        ),
        migrations.CreateModel(
            name='MatchingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Соедините элементы', max_length=200, verbose_name='Заголовок')),
            ],
        ),
        migrations.RemoveField(
            model_name='lessoncomponent',
            name='conspectus_component',
        ),
        migrations.RemoveField(
            model_name='lessoncomponent',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessoncomponent',
            name='question_component',
        ),
        migrations.RemoveField(
            model_name='lessoncomponent',
            name='video_component',
        ),
        migrations.AlterModelOptions(
            name='questioncomponent',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос компонент', 'verbose_name_plural': 'Вопросы компоненты'},
        ),
        migrations.CreateModel(
            name='FillTextLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api_lessons.filltextcomponent', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Строка компонента заполните текст',
                'verbose_name_plural': 'Строки компонента заполните текст',
            },
        ),
        migrations.CreateModel(
            name='FillTextLinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('just_text', models.BooleanField(default=True, verbose_name='Только текст')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ (оставьте пустым если только текст )')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api_lessons.filltextline', verbose_name='Строка')),
            ],
            options={
                'verbose_name': 'Часть строки компонента заполните текст',
                'verbose_name_plural': 'Части строки компонента заполните текст',
            },
        ),
        migrations.CreateModel(
            name='LessonPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок страницы в уроке')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api_lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Страница урока',
                'verbose_name_plural': 'Страницы урока',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.CharField(blank=True, default='Изображение', max_length=200, null=True, verbose_name='Описание')),
                ('image', protected_media.models.ProtectedImageField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='images/', verbose_name='Изображение')),
                ('lesson_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока')),
            ],
            options={
                'verbose_name': 'Изображение компонент',
                'verbose_name_plural': 'Изображения компоненты',
            },
        ),
        migrations.CreateModel(
            name='AudioComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(default='Аудио', max_length=200, verbose_name='Заголовок')),
                ('audio', protected_media.models.ProtectedImageField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='audio/', verbose_name='Аудио файл')),
                ('lesson_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока')),
            ],
            options={
                'verbose_name': 'Аудио компонент',
                'verbose_name_plural': 'Аудио компоненты',
            },
        ),
        migrations.DeleteModel(
            name='ConspectusComponent',
        ),
        migrations.DeleteModel(
            name='LessonComponent',
        ),
    ]
