# Generated by Django 5.0.2 on 2024-05-22 21:30

import django.db.models.deletion
import protected_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0020_filltextcomponent_matchingcomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingComponentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст элемента')),
                ('image', protected_media.models.ProtectedImageField(blank=True, null=True, storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='matching_elements/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Элемент соединения',
                'verbose_name_plural': 'Элементы соединения',
            },
        ),
        migrations.AlterModelOptions(
            name='matchingcomponent',
            options={'verbose_name': 'Соедините элементы компонент', 'verbose_name_plural': 'Соедините элементы компоненты'},
        ),
        migrations.RemoveField(
            model_name='filltextlinepart',
            name='just_text',
        ),
        migrations.AddField(
            model_name='filltextcomponent',
            name='lesson_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filltextcomponent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='filltextline',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='filltextlinepart',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='filltextlinepart',
            name='put_words',
            field=models.BooleanField(default=False, verbose_name='Подставить слова'),
        ),
        migrations.AddField(
            model_name='matchingcomponent',
            name='lesson_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchingcomponent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='questioncomponent',
            name='lesson_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncomponent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='videocomponent',
            name='lesson_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocomponent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='audiocomponent',
            name='audio',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='audio/', verbose_name='Аудио файл'),
        ),
        migrations.CreateModel(
            name='MatchingComponentElementCouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_element', to='api_lessons.matchingcomponentelement', verbose_name='Первый элемент')),
                ('second_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_element', to='api_lessons.matchingcomponentelement', verbose_name='Второй элемент')),
            ],
            options={
                'verbose_name': 'Пара элементов соединения',
                'verbose_name_plural': 'Пары элементов соединения',
            },
        ),
    ]
