# Generated by Django 5.0.2 on 2024-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0021_matchingcomponentelement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='topic',
            new_name='title',
        ),
    ]
