# Generated by Django 5.0.2 on 2024-05-22 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0022_rename_topic_lesson_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueCardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(default='Текст', verbose_name='Текст')),
                ('lesson_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока')),
            ],
            options={
                'verbose_name': 'Blue Card компонент',
                'verbose_name_plural': 'Blue Card компоненты',
            },
        ),
        migrations.CreateModel(
            name='PutInOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(default='Поставьте в правильном порядке', max_length=200, verbose_name='Заголовок')),
                ('lesson_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока')),
            ],
            options={
                'verbose_name': 'Поставьте в правильном порядке компонент',
                'verbose_name_plural': 'Поставьте в правильном порядке компоненты',
            },
        ),
        migrations.CreateModel(
            name='PutInOrderComponentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст элемента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api_lessons.putinordercomponent', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Элемент компонента поставьте в правильном порядке',
                'verbose_name_plural': 'Элементы компонента поставьте в правильном порядке',
            },
        ),
        migrations.CreateModel(
            name='RecordAudioComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('lesson_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока')),
            ],
            options={
                'verbose_name': 'Запись аудио компонент',
                'verbose_name_plural': 'Запись аудио компоненты',
            },
        ),
        migrations.CreateModel(
            name='TextComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('lesson_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='api_lessons.lessonpage', verbose_name='Страница урока')),
            ],
            options={
                'verbose_name': 'Текст компонент',
                'verbose_name_plural': 'Текст компоненты',
            },
        ),
        migrations.CreateModel(
            name='UserRecordAudioComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/', verbose_name='Аудио файл')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий учителя')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='api_lessons.recordaudiocomponent', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Запись аудио компонент',
                'verbose_name_plural': 'Запись аудио компоненты',
            },
        ),
    ]
