# Generated by Django 5.0.2 on 2024-05-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0023_bluecardcomponent_putinordercomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='bluecardcomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='filltextcomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='imagecomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='matchingcomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='putinordercomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='questioncomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='recordaudiocomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='textcomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='videocomponent',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
