# Generated by Django 5.0.2 on 2024-05-22 23:11

import backend.global_function
import protected_media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0024_alter_audiocomponent_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocomponent',
            name='audio',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=backend.global_function.PathAndRename('audio/'), verbose_name='Аудио файл'),
        ),
    ]
