# Generated by Django 5.0.2 on 2024-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0025_alter_audiocomponent_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='filltextline',
            name='answer',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ответ (оставьте пустым если только текст )'),
        ),
        migrations.AddField(
            model_name='filltextline',
            name='put_words',
            field=models.BooleanField(default=False, verbose_name='Подставить слова'),
        ),
        migrations.AddField(
            model_name='filltextline',
            name='text_after',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Текст после'),
        ),
        migrations.AddField(
            model_name='filltextline',
            name='text_before',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Текст'),
        ),
        migrations.DeleteModel(
            name='FillTextLinePart',
        ),
    ]
