# Generated by Django 5.0.2 on 2024-05-23 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0026_filltextline_answer_filltextline_put_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='audiocomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='bluecardcomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='bluecardcomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='filltextcomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='filltextcomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='matchingcomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='matchingcomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='putinordercomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='putinordercomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='questioncomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='questioncomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='recordaudiocomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='recordaudiocomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='videocomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='videocomponent',
            name='order',
        ),
        migrations.CreateModel(
            name='PageLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api_lessons.lessonpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Строка страницы',
                'verbose_name_plural': 'Строки страницы',
                'ordering': ['order'],
            },
        ),
    ]
