# Generated by Django 5.0.2 on 2024-05-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0027_remove_audiocomponent_lesson_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioComponent',
        ),
        migrations.DeleteModel(
            name='BlueCardComponent',
        ),
        migrations.RemoveField(
            model_name='filltextline',
            name='component',
        ),
        migrations.DeleteModel(
            name='ImageComponent',
        ),
        migrations.RemoveField(
            model_name='lessonpage',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='pageline',
            name='page',
        ),
        migrations.DeleteModel(
            name='MatchingComponent',
        ),
        migrations.RemoveField(
            model_name='matchingcomponentelementcouple',
            name='first_element',
        ),
        migrations.RemoveField(
            model_name='matchingcomponentelementcouple',
            name='second_element',
        ),
        migrations.RemoveField(
            model_name='putinordercomponentelement',
            name='component',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionmodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userrecordaudiocomponent',
            name='component',
        ),
        migrations.DeleteModel(
            name='TextComponent',
        ),
        migrations.RemoveField(
            model_name='userquestionmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='VideoComponent',
        ),
        migrations.DeleteModel(
            name='FillTextComponent',
        ),
        migrations.DeleteModel(
            name='FillTextLine',
        ),
        migrations.DeleteModel(
            name='LessonPage',
        ),
        migrations.DeleteModel(
            name='PageLine',
        ),
        migrations.DeleteModel(
            name='MatchingComponentElement',
        ),
        migrations.DeleteModel(
            name='MatchingComponentElementCouple',
        ),
        migrations.DeleteModel(
            name='PutInOrderComponent',
        ),
        migrations.DeleteModel(
            name='PutInOrderComponentElement',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionComponent',
        ),
        migrations.DeleteModel(
            name='RecordAudioComponent',
        ),
        migrations.DeleteModel(
            name='UserRecordAudioComponent',
        ),
        migrations.DeleteModel(
            name='UserQuestionModel',
        ),
    ]
