# Generated by Django 5.0.2 on 2024-05-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0031_alter_audiocomponent_lesson_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='bluecardcomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='recordaudiocomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='questioncomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='putinordercomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='audiocomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='matchingcomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='videocomponent',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='filltextcomponent',
            name='lesson_page',
        ),
        migrations.DeleteModel(
            name='LessonPageElement',
        ),
    ]
