# Generated by Django 5.0.2 on 2024-05-23 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0032_remove_imagecomponent_lesson_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок элемента на странице')),
                ('audio_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.audiocomponent')),
                ('bluecard_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.bluecardcomponent')),
                ('filltext_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.filltextcomponent')),
                ('image_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.imagecomponent')),
                ('matching_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.matchingcomponent')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api_lessons.lessonpage', verbose_name='Страница')),
                ('putinorder_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.putinordercomponent')),
                ('question_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.questioncomponent')),
                ('recordaudio_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.recordaudiocomponent')),
                ('text_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.textcomponent')),
                ('video_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.videocomponent')),
            ],
            options={
                'verbose_name': 'Элемент страницы урока',
                'verbose_name_plural': 'Элементы страницы урока',
                'ordering': ['order'],
            },
        ),
    ]
