# Generated by Django 5.0.2 on 2024-05-23 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0033_lessonpageelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpageelement',
            name='audio_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.audiocomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='bluecard_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.bluecardcomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='filltext_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.filltextcomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='image_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.imagecomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='matching_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.matchingcomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='putinorder_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.putinordercomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='question_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.questioncomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='recordaudio_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.recordaudiocomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='text_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.textcomponent'),
        ),
        migrations.AlterField(
            model_name='lessonpageelement',
            name='video_component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_element', to='api_lessons.videocomponent'),
        ),
    ]
