# Generated by Django 5.0.2 on 2024-05-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0034_alter_lessonpageelement_audio_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingcomponentelementcouple',
            name='component',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='element_couples', to='api_lessons.matchingcomponent', verbose_name='Компонент'),
            preserve_default=False,
        ),
    ]
