# Generated by Django 5.0.2 on 2024-05-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0035_matchingcomponentelementcouple_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingcomponentelementcouple',
            name='first_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_element', to='api_lessons.matchingcomponentelement', verbose_name='Первый элемент'),
        ),
        migrations.AlterField(
            model_name='matchingcomponentelementcouple',
            name='second_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_element', to='api_lessons.matchingcomponentelement', verbose_name='Второй элемент'),
        ),
    ]
