# Generated by Django 5.0.2 on 2024-05-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0036_alter_matchingcomponentelementcouple_first_element_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonpageelement',
            old_name='bluecard_component',
            new_name='blue_card_component',
        ),
        migrations.RenameField(
            model_name='lessonpageelement',
            old_name='filltext_component',
            new_name='fill_text_component',
        ),
        migrations.RenameField(
            model_name='lessonpageelement',
            old_name='putinorder_component',
            new_name='put_in_order_component',
        ),
        migrations.RenameField(
            model_name='lessonpageelement',
            old_name='recordaudio_component',
            new_name='record_audio_component',
        ),
    ]
