# Generated by Django 5.0.2 on 2024-05-23 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0001_squashed_0038_alter_userrecordaudiocomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(verbose_name='Порядок урока в коллекции'),
        ),
        migrations.AlterField(
            model_name='matchingcomponentelementcouple',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_couples', to='api_lessons.matchingcomponent', verbose_name='Компонент'),
        ),
    ]
