# Generated by Django 5.0.2 on 2024-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0039_alter_lesson_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filltextline',
            name='put_words',
        ),
        migrations.AddField(
            model_name='filltextcomponent',
            name='put_words',
            field=models.BooleanField(default=False, verbose_name='Перетаскивание слов'),
        ),
    ]
