# Generated by Django 5.0.2 on 2024-05-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0041_userfilltextanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordaudiocomponent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='recordaudiocomponent',
            name='title',
            field=models.CharField(default='niga', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
