# Generated by Django 5.0.2 on 2024-05-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0042_recordaudiocomponent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordaudiocomponent',
            name='description',
            field=models.TextField(default='Hello!', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
