# Generated by Django 5.0.2 on 2024-05-30 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0043_alter_recordaudiocomponent_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilltextanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='userrecordaudiocomponent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='record_audio_components', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserMatchingComponentElementCouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lessons.matchingcomponentelementcouple', verbose_name='Пара элементов')),
                ('first_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_first_element', to='api_lessons.matchingcomponentelement', verbose_name='Первый элемент')),
                ('second_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_second_element', to='api_lessons.matchingcomponentelement', verbose_name='Второй элемент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_element_couples', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пара элементов соединения пользователя',
                'verbose_name_plural': 'Пары элементов соединения пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserPutInOrderAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api_lessons.putinordercomponentelement', verbose_name='Элемент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='put_in_order_answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на элемент компонента поставьте в правильном порядке',
                'verbose_name_plural': 'Ответы на элементы компонента поставьте в правильном порядке',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lessons.questionanswer', verbose_name='Ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос пользователя',
                'verbose_name_plural': 'Ответы на вопросы пользователя',
            },
        ),
    ]
