# Generated by Django 5.0.2 on 2024-05-30 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0044_userfilltextanswer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatchingcomponentelementcouple',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='userputinorderanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
