# Generated by Django 5.0.2 on 2024-05-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0045_usermatchingcomponentelementcouple_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatchingcomponentelementcouple',
            name='second_element',
        ),
    ]
