# Generated by Django 5.0.2 on 2024-05-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0046_remove_usermatchingcomponentelementcouple_second_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfilltextanswer',
            options={'verbose_name': '[Ответ] Строка компонента заполните текст', 'verbose_name_plural': '[Ответы] Строки компонента заполните текст'},
        ),
        migrations.AlterModelOptions(
            name='usermatchingcomponentelementcouple',
            options={'verbose_name': '[Ответ] Пара элементов соединения', 'verbose_name_plural': '[Ответ] Пары элементов соединения'},
        ),
        migrations.AlterModelOptions(
            name='userputinorderanswer',
            options={'verbose_name': '[Ответ] Элемент компонента поставьте в правильном порядке', 'verbose_name_plural': '[Ответы] Элементы компонента поставьте в правильном порядке'},
        ),
        migrations.AlterModelOptions(
            name='userquestionanswer',
            options={'verbose_name': '[Ответ] Вопрос компонент', 'verbose_name_plural': '[Ответы] Вопросы компонент'},
        ),
        migrations.AlterModelOptions(
            name='userrecordaudiocomponent',
            options={'verbose_name': '[Ответ] Аудио компонент', 'verbose_name_plural': '[Ответ] Аудио компоненты'},
        ),
    ]
