# Generated by Django 5.0.2 on 2024-05-31 15:42

import backend.global_function
import protected_media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0048_alter_userrecordaudiocomponent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocomponent',
            name='audio',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=backend.global_function.PathAndRename('audio_components/'), verbose_name='Аудио файл'),
        ),
        migrations.AlterField(
            model_name='matchingcomponentelement',
            name='image',
            field=protected_media.models.ProtectedImageField(blank=True, null=True, storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=backend.global_function.PathAndRename('matching_elements/'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userrecordaudiocomponent',
            name='file',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=backend.global_function.PathAndRename(path='record_component_answer/'), verbose_name='Аудио файл'),
        ),
    ]
