# Generated by Django 5.0.2 on 2024-06-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0049_alter_audiocomponent_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatchingcomponentelementcouple',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_couples', to='api_lessons.matchingcomponentelementcouple', verbose_name='Пара элементов'),
        ),
    ]
