# Generated by Django 5.0.2 on 2024-06-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0050_alter_usermatchingcomponentelementcouple_couple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api_lessons.questionanswer', verbose_name='Ответ'),
        ),
    ]
