# Generated by Django 5.0.2 on 2024-06-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0051_alter_userquestionanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='question',
            new_name='component',
        ),
    ]
