# Generated by Django 5.0.2 on 2024-06-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0052_rename_question_questionanswer_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filltextline',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
    ]
