# Generated by Django 5.0.2 on 2024-06-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0053_alter_filltextline_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Урок', 'verbose_name_plural': '2 Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonbatch',
            options={'verbose_name': 'Коллекция уроков', 'verbose_name_plural': '1 Коллекции уроков'},
        ),
        migrations.AlterField(
            model_name='putinordercomponentelement',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
    ]
