# Generated by Django 5.0.2 on 2024-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0054_alter_lesson_options_alter_lessonbatch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoUrlCacheModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_link', models.URLField(verbose_name='Ссылка на видео')),
                ('playable_video_link', models.URLField(verbose_name='Ссылка на видеофайл')),
                ('expire_time', models.DateTimeField(verbose_name='Время истечения ссылки')),
            ],
            options={
                'verbose_name': 'Кэш ссылок Vimeo',
                'verbose_name_plural': 'Кэш ссылок Vimeo',
            },
        ),
    ]
