# Generated by Django 5.0.2 on 2024-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0056_alter_filltextline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default="This is lesson's description, please fill out this field", max_length=4096, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlessonmodel',
            name='review_comment',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Комментарий к уроку'),
        ),
        migrations.AddField(
            model_name='userlessonmodel',
            name='review_mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка урока'),
        ),
    ]
