# Generated by Django 5.0.2 on 2024-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0057_lesson_description_userlessonmodel_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessonmodel',
            name='review_comment',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Комментарий к уроку'),
            preserve_default=False,
        ),
    ]
