# Generated by Django 5.0.2 on 2024-05-06 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000, verbose_name='Текст вопроса')),
                ('needs_answer', models.BooleanField(default=True, verbose_name='Требуется ответ')),
            ],
            options={
                'verbose_name': 'Вопрос (Дата коллекция)',
                'verbose_name_plural': 'Вопросы (Дата коллекция)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DCQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=2000, verbose_name='Текст ответа')),
                ('answered_users', models.ManyToManyField(related_name='answers_to_dc_questions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи ответившие на вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api_data_collection.dcquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос (Дата коллекция)',
                'verbose_name_plural': 'Ответы на вопросы (Дата коллекция)',
                'ordering': ['id'],
            },
        ),
    ]
