# Generated by Django 5.0.1 on 2024-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='finished_users',
            field=models.ManyToManyField(blank=True, related_name='finished_quiz_questions', to='api_tasks.usertasksprofile', verbose_name='Закончившие вопрос'),
        ),
    ]
