# Generated by Django 5.0.1 on 2024-04-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0002_alter_quizquestion_finished_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'verbose_name': 'Опрос: вопрос', 'verbose_name_plural': 'Опрос: вопросы'},
        ),
        migrations.AlterModelOptions(
            name='usersurveyanswer',
            options={'verbose_name': 'Опрос: ответ', 'verbose_name_plural': 'Опрос: ответы'},
        ),
        migrations.AlterField(
            model_name='usertasksprofile',
            name='completed_quizzes',
            field=models.ManyToManyField(related_name='completed_users', to='api_tasks.quizbatch', verbose_name='Пройденные викторины'),
        ),
    ]
