# Generated by Django 5.0.1 on 2024-04-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0003_alter_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurveyanswer',
            name='user_tasks_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tasks.usertasksprofile', verbose_name='Пользователь'),
        ),
    ]
