# Generated by Django 5.0.1 on 2024-04-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0004_alter_usersurveyanswer_user_tasks_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurveyanswer',
            name='user_tasks_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='api_tasks.usertasksprofile', verbose_name='Пользователь'),
        ),
    ]
