# Generated by Django 5.0.1 on 2024-04-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0005_alter_usersurveyanswer_user_tasks_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizbatch',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='quizquestionanswer',
            name='answer',
            field=models.CharField(max_length=2000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.CharField(max_length=2000, verbose_name='Вопрос'),
        ),
    ]
