# Generated by Django 5.0.1 on 2024-04-08 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0006_alter_quizbatch_name_alter_quizquestionanswer_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_earned', models.IntegerField(default=0, verbose_name='Заработанные монеты')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tasks.quizquestionanswer', verbose_name='Ответ')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api_tasks.quizquestion', verbose_name='Вопрос')),
                ('user_tasks_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='api_tasks.usertasksprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос викторины',
                'verbose_name_plural': 'Ответы на вопросы викторины',
            },
        ),
    ]
