# Generated by Django 5.0.1 on 2024-04-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0007_userquizquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='finished_users',
        ),
    ]
