# Generated by Django 5.0.2 on 2024-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_global_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaleventmodel',
            name='type',
            field=models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('bars', 'Bars')], max_length=255, verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='GlobalEventTypeModel',
        ),
    ]
