# Generated by Django 5.0.2 on 2024-07-01 23:04

import backend.global_function
import django.db.models.deletion
import protected_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAudioComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Аудио', max_length=200, verbose_name='Заголовок')),
                ('audio', protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=backend.global_function.PathAndRename('additional_audio_components/'), verbose_name='Аудио файл')),
            ],
            options={
                'verbose_name': 'Аудио компонент',
                'verbose_name_plural': 'Аудио компоненты',
            },
        ),
        migrations.CreateModel(
            name='AdditionalImageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Изображение', max_length=200, null=True, verbose_name='Описание')),
                ('image', protected_media.models.ProtectedImageField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=backend.global_function.PathAndRename('additional_images/'), verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение компонент',
                'verbose_name_plural': 'Изображения компоненты',
            },
        ),
        migrations.CreateModel(
            name='AdditionalLessonBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalTextComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст компонент',
                'verbose_name_plural': 'Текст компоненты',
            },
        ),
        migrations.CreateModel(
            name='AdditionalVideoComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видео компонент',
                'verbose_name_plural': 'Видео компоненты',
            },
        ),
        migrations.CreateModel(
            name='AdditionalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('order', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lesson_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api_additional_materials.additionallessonbatch')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalLessonElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок элемента на уроке')),
                ('audio_component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_lesson_element', to='api_additional_materials.additionalaudiocomponent')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api_additional_materials.additionallesson', verbose_name='Страница')),
                ('video_component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_lesson_element', to='api_additional_materials.additionalimagecomponent')),
                ('text_component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_lesson_element', to='api_additional_materials.additionaltextcomponent')),
                ('image_component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_lesson_element', to='api_additional_materials.additionalvideocomponent')),
            ],
            options={
                'verbose_name': 'Элемент страницы урока',
                'verbose_name_plural': 'Элементы страницы урока',
                'ordering': ['order'],
            },
        ),
    ]
